package com.kt.mindLog.domain.summary;

public enum EmotionType {
	SERENITY, JOY, ECSTASY,
	ACCEPTANCE, TRUST, ADMIRATION,
	APPREHENSION, FEAR, TERROR,
	DISTRACTION, SURPRISE, AMAZEMENT,
	PENSIVENESS, SADNESS, GRIEF,
	BOREDOM, DISGUST, LOATHING,
	ANNOYANCE, ANGER, RAGE,
	INTEREST, ANTICIPATION, VIGILANCE
}