spring:
  application:
    name: mindLog

  datasource:
    url: jdbc:postgresql://localhost:5432/mindLog
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080