spring:
  application:
    name: mindLog

  datasource:
    url: jdbc:mysql://localhost:3306/mindLog
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080